### ISSUE TITLE
bpftrace build is failing after upstream change added new dependency

### ISSUE THREAD

**Issue by jgallag88** [delphix/linux-pkg#10] opened 2019-01-13 20:06 UTC
A recent upstream commit added a new dependency for bpftrace: https://github.com/iovisor/bpftrace/pull/327.  On Ubuntu, the new dependency is called `libbpfcc-dev`. Unfortunately, the build still fails even when that packages is installed: https://github.com/iovisor/bpftrace/pull/335#issuecomment-453854901.

I notice that bpftrace does build and run if bcc is built and installed from source, or if the `libbcc` package is installed from the IO Visor apt repo (https://repo.iovisor.org/apt/bionic).

**Comment by pzakha** [comment] 2019-01-14 17:35
If we install the `libbcc` package from Iovisor, the produced `bpftrace` package is then dependent on `libbcc`, which must be fetched from Iovisor's PPA. I'm reluctant in adding extra PPA dependencies, so I'd propose we wait for updates from Iovisor.

**Comment by danobi** [comment] 2019-01-15 21:49
I looked into this and it appears Ubuntu 18.04's `libbpfcc-dev` is too old. I think the issue is fixed in the latest debian (testing?). Until the change propagates down, I think you might have to have your own bcc package.

**Comment by pzakha** [comment] 2019-01-15 21:53
@danobi Thanks for looking into it. That's probably what we'll do now that we are aware of the internals of `bpftrace`. Our idea was to have a reproducible build, and fetching an arbitrary "latest" version from https://github.com/iovisor/bcc at build time was defeating that model anyway.

**Comment by pzakha** [comment] 2019-02-22 18:54
fixed by #12

**Closed by pzakha** 2019-02-22 18:54 UTC
